# Numerai Tournament Configuration

# API Credentials (can also be set via environment variables NUMERAI_PUBLIC_ID and NUMERAI_SECRET_KEY)
# Uncomment and set these values if not using environment variables
# api_public_key = "YOUR_PUBLIC_KEY_HERE"
# api_secret_key = "YOUR_SECRET_KEY_HERE"

# Tournament Configuration
# 8 = Classic Tournament (default)
# 11 = Signals Tournament
tournament_id = 8

# Model names to manage (leave empty to auto-discover from your Numerai account)
models = []

# Data storage directories
data_dir = "data"
model_dir = "models"

# Automation settings
auto_submit = true
stake_amount = 0.0

# Feature set configuration
# Options: "small" (~300 features), "medium" (~1000 features), "all" (~5000 features)
feature_set = "medium"