# Numerai Tournament Configuration

# Model names to manage
models = ["example_model"]

# Data storage directories
data_dir = "data"
model_dir = "models"

# Automation settings
auto_submit = false
stake_amount = 0.0

# System resources
max_workers = 8
notification_enabled = true